-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Autor Script:                 RaulEBC
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table companies.comunas
CREATE TABLE IF NOT EXISTS `comunas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comuna` varchar(64) NOT NULL,
  `provincia_id` int(8) NOT NULL,
  `region_id` int(8) DEFAULT NULL,
  `provincia` varchar(50) DEFAULT NULL,
  `region` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=348 DEFAULT CHARSET=utf8;

-- Dumping data for table companies.comunas: 346 rows
DELETE FROM `comunas`;
/*!40000 ALTER TABLE `comunas` DISABLE KEYS */;
INSERT INTO `comunas` (`id`, `comuna`, `provincia_id`, `region_id`, `provincia`, `region`) VALUES
	(1, 'Arica', 1, 1, 'Arica', 'Arica y Parinacota'),
	(2, 'Camarones', 1, 1, 'Arica', 'Arica y Parinacota'),
	(3, 'General Lagos', 2, 1, 'Parinacota', 'Arica y Parinacota'),
	(4, 'Putre', 2, 1, 'Parinacota', 'Arica y Parinacota'),
	(5, 'Alto Hospicio', 3, 2, 'Iquique', 'Tarapacá'),
	(6, 'Iquique', 3, 2, 'Iquique', 'Tarapacá'),
	(7, 'Camiña', 4, 2, 'El Tamarugal', 'Tarapacá'),
	(8, 'Colchane', 4, 2, 'El Tamarugal', 'Tarapacá'),
	(9, 'Huara', 4, 2, 'El Tamarugal', 'Tarapacá'),
	(10, 'Pica', 4, 2, 'El Tamarugal', 'Tarapacá'),
	(11, 'Pozo Almonte', 4, 2, 'El Tamarugal', 'Tarapacá'),
	(12, 'Tocopilla', 5, 3, 'Tocopilla', 'Antofagasta'),
	(13, 'María Elena', 5, 3, 'Tocopilla', 'Antofagasta'),
	(14, 'Calama', 6, 3, 'El Loa', 'Antofagasta'),
	(15, 'Ollague', 6, 3, 'El Loa', 'Antofagasta'),
	(16, 'San Pedro de Atacama', 6, 3, 'El Loa', 'Antofagasta'),
	(17, 'Antofagasta', 7, 3, 'Antofagasta', 'Antofagasta'),
	(18, 'Mejillones', 7, 3, 'Antofagasta', 'Antofagasta'),
	(19, 'Sierra Gorda', 7, 3, 'Antofagasta', 'Antofagasta'),
	(20, 'Taltal', 7, 3, 'Antofagasta', 'Antofagasta'),
	(21, 'Chañaral', 8, 4, 'Chañaral', 'Atacama'),
	(22, 'Diego de Almagro', 8, 4, 'Chañaral', 'Atacama'),
	(23, 'Copiapó', 9, 4, 'Copiapó', 'Atacama'),
	(24, 'Caldera', 9, 4, 'Copiapó', 'Atacama'),
	(25, 'Tierra Amarilla', 9, 4, 'Copiapó', 'Atacama'),
	(26, 'Vallenar', 10, 4, 'Huasco', 'Atacama'),
	(27, 'Alto del Carmen', 10, 4, 'Huasco', 'Atacama'),
	(28, 'Freirina', 10, 4, 'Huasco', 'Atacama'),
	(29, 'Huasco', 10, 4, 'Huasco', 'Atacama'),
	(30, 'La Serena', 11, 5, 'Elqui', 'Coquimbo'),
	(31, 'Coquimbo', 11, 5, 'Elqui', 'Coquimbo'),
	(32, 'Andacollo', 11, 5, 'Elqui', 'Coquimbo'),
	(33, 'La Higuera', 11, 5, 'Elqui', 'Coquimbo'),
	(34, 'Paihuano', 11, 5, 'Elqui', 'Coquimbo'),
	(35, 'Vicuña', 11, 5, 'Elqui', 'Coquimbo'),
	(36, 'Ovalle', 12, 5, 'Limarí', 'Coquimbo'),
	(37, 'Combarbalá', 12, 5, 'Limarí', 'Coquimbo'),
	(38, 'Monte Patria', 12, 5, 'Limarí', 'Coquimbo'),
	(39, 'Punitaqui', 12, 5, 'Limarí', 'Coquimbo'),
	(40, 'Río Hurtado', 12, 5, 'Limarí', 'Coquimbo'),
	(41, 'Illapel', 13, 5, 'Choapa', 'Coquimbo'),
	(42, 'Canela', 13, 5, 'Choapa', 'Coquimbo'),
	(43, 'Los Vilos', 13, 5, 'Choapa', 'Coquimbo'),
	(44, 'Salamanca', 13, 5, 'Choapa', 'Coquimbo'),
	(45, 'La Ligua', 14, 6, 'Petorca', 'Valparaiso'),
	(46, 'Cabildo', 14, 6, 'Petorca', 'Valparaiso'),
	(47, 'Zapallar', 14, 6, 'Petorca', 'Valparaiso'),
	(48, 'Papudo', 14, 6, 'Petorca', 'Valparaiso'),
	(49, 'Petorca', 14, 6, 'Petorca', 'Valparaiso'),
	(50, 'Los Andes', 15, 6, 'Los Andes', 'Valparaiso'),
	(51, 'San Esteban', 15, 6, 'Los Andes', 'Valparaiso'),
	(52, 'Calle Larga', 15, 6, 'Los Andes', 'Valparaiso'),
	(53, 'Rinconada', 15, 6, 'Los Andes', 'Valparaiso'),
	(54, 'San Felipe', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(55, 'Llaillay', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(56, 'Putaendo', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(57, 'Santa María', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(58, 'Catemu', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(59, 'Panquehue', 16, 6, 'San Felipe de Aconcagua', 'Valparaiso'),
	(60, 'Quillota', 17, 6, 'Quillota', 'Valparaiso'),
	(61, 'La Cruz', 17, 6, 'Quillota', 'Valparaiso'),
	(62, 'La Calera', 17, 6, 'Quillota', 'Valparaiso'),
	(63, 'Nogales', 17, 6, 'Quillota', 'Valparaiso'),
	(64, 'Hijuelas', 17, 6, 'Quillota', 'Valparaiso'),
	(65, 'Valparaíso', 18, 6, 'Valparaiso', 'Valparaiso'),
	(66, 'Viña del Mar', 18, 6, 'Valparaiso', 'Valparaiso'),
	(67, 'Concón', 18, 6, 'Valparaiso', 'Valparaiso'),
	(68, 'Quintero', 18, 6, 'Valparaiso', 'Valparaiso'),
	(69, 'Puchuncaví', 18, 6, 'Valparaiso', 'Valparaiso'),
	(70, 'Casablanca', 18, 6, 'Valparaiso', 'Valparaiso'),
	(71, 'Juan Fernández', 18, 6, 'Valparaiso', 'Valparaiso'),
	(72, 'San Antonio', 19, 6, 'San Antonio', 'Valparaiso'),
	(73, 'Cartagena', 19, 6, 'San Antonio', 'Valparaiso'),
	(74, 'El Tabo', 19, 6, 'San Antonio', 'Valparaiso'),
	(75, 'El Quisco', 19, 6, 'San Antonio', 'Valparaiso'),
	(76, 'Algarrobo', 19, 6, 'San Antonio', 'Valparaiso'),
	(77, 'Santo Domingo', 19, 6, 'San Antonio', 'Valparaiso'),
	(78, 'Isla de Pascua', 20, 6, 'Isla de Pascua', 'Valparaiso'),
	(79, 'Quilpué', 21, 6, 'Marga Marga', 'Valparaiso'),
	(80, 'Limache', 21, 6, 'Marga Marga', 'Valparaiso'),
	(81, 'Olmué', 21, 6, 'Marga Marga', 'Valparaiso'),
	(82, 'Villa Alemana', 21, 6, 'Marga Marga', 'Valparaiso'),
	(83, 'Colina', 22, 7, 'Chacabuco', 'Metropolitana de Santiago'),
	(84, 'Lampa', 22, 7, 'Chacabuco', 'Metropolitana de Santiago'),
	(85, 'Tiltil', 22, 7, 'Chacabuco', 'Metropolitana de Santiago'),
	(86, 'Santiago', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(87, 'Vitacura', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(88, 'San Ramón', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(89, 'San Miguel', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(90, 'San Joaquín', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(91, 'Renca', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(92, 'Recoleta', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(93, 'Quinta Normal', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(94, 'Quilicura', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(95, 'Pudahuel', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(96, 'Providencia', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(97, 'Peñalolén', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(98, 'Pedro Aguirre Cerda', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(99, 'Ñuñoa', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(100, 'Maipú', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(101, 'Macul', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(102, 'Lo Prado', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(103, 'Lo Espejo', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(104, 'Lo Barnechea', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(105, 'Las Condes', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(106, 'La Reina', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(107, 'La Pintana', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(108, 'La Granja', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(109, 'La Florida', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(110, 'La Cisterna', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(111, 'Independencia', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(112, 'Huechuraba', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(113, 'Estación Central', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(114, 'El Bosque', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(115, 'Conchalí', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(116, 'Cerro Navia', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(117, 'Cerrillos', 23, 7, 'Santiago', 'Metropolitana de Santiago'),
	(118, 'Puente Alto', 24, 7, 'Cordillera', 'Metropolitana de Santiago'),
	(119, 'San José de Maipo', 24, 7, 'Cordillera', 'Metropolitana de Santiago'),
	(120, 'Pirque', 24, 7, 'Cordillera', 'Metropolitana de Santiago'),
	(121, 'San Bernardo', 25, 7, 'Maipo', 'Metropolitana de Santiago'),
	(122, 'Buin', 25, 7, 'Maipo', 'Metropolitana de Santiago'),
	(123, 'Paine', 25, 7, 'Maipo', 'Metropolitana de Santiago'),
	(124, 'Calera de Tango', 25, 7, 'Maipo', 'Metropolitana de Santiago'),
	(125, 'Melipilla', 26, 7, 'Melipilla', 'Metropolitana de Santiago'),
	(126, 'Alhué', 26, 7, 'Melipilla', 'Metropolitana de Santiago'),
	(127, 'Curacaví', 26, 7, 'Melipilla', 'Metropolitana de Santiago'),
	(128, 'María Pinto', 26, 7, 'Melipilla', 'Metropolitana de Santiago'),
	(129, 'San Pedro', 26, 7, 'Melipilla', 'Metropolitana de Santiago'),
	(130, 'Isla de Maipo', 27, 7, 'Talagante', 'Metropolitana de Santiago'),
	(131, 'El Monte', 27, 7, 'Talagante', 'Metropolitana de Santiago'),
	(132, 'Padre Hurtado', 27, 7, 'Talagante', 'Metropolitana de Santiago'),
	(133, 'Peñaflor', 27, 7, 'Talagante', 'Metropolitana de Santiago'),
	(134, 'Talagante', 27, 7, 'Talagante', 'Metropolitana de Santiago'),
	(135, 'Codegua', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(136, 'Coínco', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(137, 'Coltauco', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(138, 'Doñihue', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(139, 'Graneros', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(140, 'Las Cabras', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(141, 'Machalí', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(142, 'Malloa', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(143, 'Mostazal', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(144, 'Olivar', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(145, 'Peumo', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(146, 'Pichidegua', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(147, 'Quinta de Tilcoco', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(148, 'Rancagua', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(149, 'Rengo', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(150, 'Requínoa', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(151, 'San Vicente de Tagua Tagua', 28, 8, 'Cachapoal', 'Libertador General Bernardo O\'Higgins'),
	(152, 'Chépica', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(153, 'Chimbarongo', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(154, 'Lolol', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(155, 'Nancagua', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(156, 'Palmilla', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(157, 'Peralillo', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(158, 'Placilla', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(159, 'Pumanque', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(160, 'San Fernando', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(161, 'Santa Cruz', 29, 8, 'Colchagua', 'Libertador General Bernardo O\'Higgins'),
	(162, 'La Estrella', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(163, 'Litueche', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(164, 'Marchigüe', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(165, 'Navidad', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(166, 'Paredones', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(167, 'Pichilemu', 30, 8, 'Cardenal Caro', 'Libertador General Bernardo O\'Higgins'),
	(168, 'Curicó', 31, 9, 'Curicó', 'Maule'),
	(169, 'Hualañé', 31, 9, 'Curicó', 'Maule'),
	(170, 'Licantén', 31, 9, 'Curicó', 'Maule'),
	(171, 'Molina', 31, 9, 'Curicó', 'Maule'),
	(172, 'Rauco', 31, 9, 'Curicó', 'Maule'),
	(173, 'Romeral', 31, 9, 'Curicó', 'Maule'),
	(174, 'Sagrada Familia', 31, 9, 'Curicó', 'Maule'),
	(175, 'Teno', 31, 9, 'Curicó', 'Maule'),
	(176, 'Vichuquén', 31, 9, 'Curicó', 'Maule'),
	(177, 'Talca', 32, 9, 'Talca', 'Maule'),
	(178, 'San Clemente', 32, 9, 'Talca', 'Maule'),
	(179, 'Pelarco', 32, 9, 'Talca', 'Maule'),
	(180, 'Pencahue', 32, 9, 'Talca', 'Maule'),
	(181, 'Maule', 32, 9, 'Talca', 'Maule'),
	(182, 'San Rafael', 32, 9, 'Talca', 'Maule'),
	(183, 'Curepto', 33, 9, 'Linares', 'Maule'),
	(184, 'Constitución', 32, 9, 'Talca', 'Maule'),
	(185, 'Empedrado', 32, 9, 'Talca', 'Maule'),
	(186, 'Río Claro', 32, 9, 'Talca', 'Maule'),
	(187, 'Linares', 33, 9, 'Linares', 'Maule'),
	(188, 'San Javier', 33, 9, 'Linares', 'Maule'),
	(189, 'Parral', 33, 9, 'Linares', 'Maule'),
	(190, 'Villa Alegre', 33, 9, 'Linares', 'Maule'),
	(191, 'Longaví', 33, 9, 'Linares', 'Maule'),
	(192, 'Colbún', 33, 9, 'Linares', 'Maule'),
	(193, 'Retiro', 33, 9, 'Linares', 'Maule'),
	(194, 'Yerbas Buenas', 33, 9, 'Linares', 'Maule'),
	(195, 'Cauquenes', 34, 9, 'Cauquenes', 'Maule'),
	(196, 'Chanco', 34, 9, 'Cauquenes', 'Maule'),
	(197, 'Pelluhue', 34, 9, 'Cauquenes', 'Maule'),
	(198, 'Bulnes', 35, 10, 'Diguillín', 'Ñuble'),
	(199, 'Chillán', 35, 10, 'Diguillín', 'Ñuble'),
	(200, 'Chillán Viejo', 35, 10, 'Diguillín', 'Ñuble'),
	(201, 'El Carmen', 35, 10, 'Diguillín', 'Ñuble'),
	(202, 'Pemuco', 35, 10, 'Diguillín', 'Ñuble'),
	(203, 'Pinto', 35, 10, 'Diguillín', 'Ñuble'),
	(204, 'Quillón', 35, 10, 'Diguillín', 'Ñuble'),
	(205, 'San Ignacio', 35, 10, 'Diguillín', 'Ñuble'),
	(206, 'Yungay', 35, 10, 'Diguillín', 'Ñuble'),
	(207, 'Cobquecura', 36, 10, 'Itata', 'Ñuble'),
	(208, 'Coelemu', 36, 10, 'Itata', 'Ñuble'),
	(209, 'Ninhue', 36, 10, 'Itata', 'Ñuble'),
	(210, 'Portezuelo', 36, 10, 'Itata', 'Ñuble'),
	(211, 'Quirihue', 36, 10, 'Itata', 'Ñuble'),
	(212, 'Ránquil', 36, 10, 'Itata', 'Ñuble'),
	(213, 'Treguaco', 36, 10, 'Itata', 'Ñuble'),
	(214, 'San Carlos', 37, 10, 'Punilla', 'Ñuble'),
	(215, 'Coihueco', 37, 10, 'Punilla', 'Ñuble'),
	(216, 'San Nicolás', 37, 10, 'Punilla', 'Ñuble'),
	(217, 'Ñiquén', 37, 10, 'Punilla', 'Ñuble'),
	(218, 'San Fabián', 37, 10, 'Punilla', 'Ñuble'),
	(219, 'Alto Biobío', 38, 11, 'Bio Bío', 'Biobío'),
	(220, 'Antuco', 38, 11, 'Bio Bío', 'Biobío'),
	(221, 'Cabrero', 38, 11, 'Bio Bío', 'Biobío'),
	(222, 'Laja', 38, 11, 'Bio Bío', 'Biobío'),
	(223, 'Los Ángeles', 38, 11, 'Bio Bío', 'Biobío'),
	(224, 'Mulchén', 38, 11, 'Bio Bío', 'Biobío'),
	(225, 'Nacimiento', 38, 11, 'Bio Bío', 'Biobío'),
	(226, 'Negrete', 38, 11, 'Bio Bío', 'Biobío'),
	(227, 'Quilaco', 38, 11, 'Bio Bío', 'Biobío'),
	(228, 'Quilleco', 38, 11, 'Bio Bío', 'Biobío'),
	(229, 'San Rosendo', 38, 11, 'Bio Bío', 'Biobío'),
	(230, 'Santa Bárbara', 38, 11, 'Bio Bío', 'Biobío'),
	(231, 'Tucapel', 38, 11, 'Bio Bío', 'Biobío'),
	(232, 'Yumbel', 38, 11, 'Bio Bío', 'Biobío'),
	(233, 'Concepción', 39, 11, 'Concepción', 'Biobío'),
	(234, 'Coronel', 39, 11, 'Concepción', 'Biobío'),
	(235, 'Chiguayante', 39, 11, 'Concepción', 'Biobío'),
	(236, 'Florida', 39, 11, 'Concepción', 'Biobío'),
	(237, 'Hualpén', 39, 11, 'Concepción', 'Biobío'),
	(238, 'Hualqui', 39, 11, 'Concepción', 'Biobío'),
	(239, 'Lota', 39, 11, 'Concepción', 'Biobío'),
	(240, 'Penco', 39, 11, 'Concepción', 'Biobío'),
	(241, 'San Pedro de La Paz', 39, 11, 'Concepción', 'Biobío'),
	(242, 'Santa Juana', 39, 11, 'Concepción', 'Biobío'),
	(243, 'Talcahuano', 39, 11, 'Concepción', 'Biobío'),
	(244, 'Tomé', 39, 11, 'Concepción', 'Biobío'),
	(245, 'Arauco', 40, 11, 'Arauco', 'Biobío'),
	(246, 'Cañete', 40, 11, 'Arauco', 'Biobío'),
	(247, 'Contulmo', 40, 11, 'Arauco', 'Biobío'),
	(248, 'Curanilahue', 40, 11, 'Arauco', 'Biobío'),
	(249, 'Lebu', 40, 11, 'Arauco', 'Biobío'),
	(250, 'Los Álamos', 40, 11, 'Arauco', 'Biobío'),
	(251, 'Tirúa', 40, 11, 'Arauco', 'Biobío'),
	(252, 'Angol', 41, 12, 'Malleco', 'La Araucanía'),
	(253, 'Collipulli', 41, 12, 'Malleco', 'La Araucanía'),
	(254, 'Curacautín', 41, 12, 'Malleco', 'La Araucanía'),
	(255, 'Ercilla', 41, 12, 'Malleco', 'La Araucanía'),
	(256, 'Lonquimay', 41, 12, 'Malleco', 'La Araucanía'),
	(257, 'Los Sauces', 41, 12, 'Malleco', 'La Araucanía'),
	(258, 'Lumaco', 41, 12, 'Malleco', 'La Araucanía'),
	(259, 'Purén', 41, 12, 'Malleco', 'La Araucanía'),
	(260, 'Renaico', 41, 12, 'Malleco', 'La Araucanía'),
	(261, 'Traiguén', 41, 12, 'Malleco', 'La Araucanía'),
	(262, 'Victoria', 41, 12, 'Malleco', 'La Araucanía'),
	(263, 'Temuco', 42, 12, 'Cautín', 'La Araucanía'),
	(264, 'Carahue', 42, 12, 'Cautín', 'La Araucanía'),
	(265, 'Cholchol', 42, 12, 'Cautín', 'La Araucanía'),
	(266, 'Cunco', 42, 12, 'Cautín', 'La Araucanía'),
	(267, 'Curarrehue', 42, 12, 'Cautín', 'La Araucanía'),
	(268, 'Freire', 42, 12, 'Cautín', 'La Araucanía'),
	(269, 'Galvarino', 42, 12, 'Cautín', 'La Araucanía'),
	(270, 'Gorbea', 42, 12, 'Cautín', 'La Araucanía'),
	(271, 'Lautaro', 42, 12, 'Cautín', 'La Araucanía'),
	(272, 'Loncoche', 42, 12, 'Cautín', 'La Araucanía'),
	(273, 'Melipeuco', 42, 12, 'Cautín', 'La Araucanía'),
	(274, 'Nueva Imperial', 42, 12, 'Cautín', 'La Araucanía'),
	(275, 'Padre Las Casas', 42, 12, 'Cautín', 'La Araucanía'),
	(276, 'Perquenco', 42, 12, 'Cautín', 'La Araucanía'),
	(277, 'Pitrufquén', 42, 12, 'Cautín', 'La Araucanía'),
	(278, 'Pucón', 42, 12, 'Cautín', 'La Araucanía'),
	(279, 'Saavedra', 42, 12, 'Cautín', 'La Araucanía'),
	(280, 'Teodoro Schmidt', 42, 12, 'Cautín', 'La Araucanía'),
	(281, 'Toltén', 42, 12, 'Cautín', 'La Araucanía'),
	(282, 'Vilcún', 42, 12, 'Cautín', 'La Araucanía'),
	(283, 'Villarrica', 42, 12, 'Cautín', 'La Araucanía'),
	(284, 'Valdivia', 43, 13, 'Valdivia', 'Los Ríos'),
	(285, 'Corral', 43, 13, 'Valdivia', 'Los Ríos'),
	(286, 'Lanco', 43, 13, 'Valdivia', 'Los Ríos'),
	(287, 'Los Lagos', 43, 13, 'Valdivia', 'Los Ríos'),
	(288, 'Máfil', 43, 13, 'Valdivia', 'Los Ríos'),
	(289, 'Mariquina', 43, 13, 'Valdivia', 'Los Ríos'),
	(290, 'Paillaco', 43, 13, 'Valdivia', 'Los Ríos'),
	(291, 'Panguipulli', 43, 13, 'Valdivia', 'Los Ríos'),
	(292, 'La Unión', 44, 13, 'Ranco', 'Los Ríos'),
	(293, 'Futrono', 44, 13, 'Ranco', 'Los Ríos'),
	(294, 'Lago Ranco', 44, 13, 'Ranco', 'Los Ríos'),
	(295, 'Río Bueno', 44, 13, 'Ranco', 'Los Ríos'),
	(297, 'Osorno', 45, 14, 'Osorno', 'Los Lagos'),
	(298, 'Puerto Octay', 45, 14, 'Osorno', 'Los Lagos'),
	(299, 'Purranque', 45, 14, 'Osorno', 'Los Lagos'),
	(300, 'Puyehue', 45, 14, 'Osorno', 'Los Lagos'),
	(301, 'Río Negro', 45, 14, 'Osorno', 'Los Lagos'),
	(302, 'San Juan de la Costa', 45, 14, 'Osorno', 'Los Lagos'),
	(303, 'San Pablo', 45, 14, 'Osorno', 'Los Lagos'),
	(304, 'Calbuco', 46, 14, 'Llanquihue', 'Los Lagos'),
	(305, 'Cochamó', 46, 14, 'Llanquihue', 'Los Lagos'),
	(306, 'Fresia', 46, 14, 'Llanquihue', 'Los Lagos'),
	(307, 'Frutillar', 46, 14, 'Llanquihue', 'Los Lagos'),
	(308, 'Llanquihue', 46, 14, 'Llanquihue', 'Los Lagos'),
	(309, 'Los Muermos', 46, 14, 'Llanquihue', 'Los Lagos'),
	(310, 'Maullín', 46, 14, 'Llanquihue', 'Los Lagos'),
	(311, 'Puerto Montt', 46, 14, 'Llanquihue', 'Los Lagos'),
	(312, 'Puerto Varas', 46, 14, 'Llanquihue', 'Los Lagos'),
	(313, 'Ancud', 47, 14, 'Chiloé', 'Los Lagos'),
	(314, 'Castro', 47, 14, 'Chiloé', 'Los Lagos'),
	(315, 'Chonchi', 47, 14, 'Chiloé', 'Los Lagos'),
	(316, 'Curaco de Vélez', 47, 14, 'Chiloé', 'Los Lagos'),
	(317, 'Dalcahue', 47, 14, 'Chiloé', 'Los Lagos'),
	(318, 'Puqueldón', 47, 14, 'Chiloé', 'Los Lagos'),
	(319, 'Queilén', 47, 14, 'Chiloé', 'Los Lagos'),
	(320, 'Quellón', 47, 14, 'Chiloé', 'Los Lagos'),
	(321, 'Quemchi', 47, 14, 'Chiloé', 'Los Lagos'),
	(322, 'Quinchao', 47, 14, 'Chiloé', 'Los Lagos'),
	(323, 'Chaitén', 48, 14, 'Palena', 'Los Lagos'),
	(324, 'Futaleufú', 48, 14, 'Palena', 'Los Lagos'),
	(325, 'Hualaihué', 48, 14, 'Palena', 'Los Lagos'),
	(326, 'Palena', 48, 14, 'Palena', 'Los Lagos'),
	(327, 'Lago Verde', 49, 15, 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo'),
	(328, 'Coihaique', 49, 15, 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo'),
	(329, 'Aysén', 50, 15, 'Aysén', 'Aysén del General Carlos Ibáñez del Campo'),
	(330, 'Cisnes', 50, 15, 'Aysén', 'Aysén del General Carlos Ibáñez del Campo'),
	(331, 'Guaitecas', 50, 15, 'Aysén', 'Aysén del General Carlos Ibáñez del Campo'),
	(332, 'Río Ibáñez', 51, 15, 'General Carrera', 'Aysén del General Carlos Ibáñez del Campo'),
	(333, 'Chile Chico', 51, 15, 'General Carrera', 'Aysén del General Carlos Ibáñez del Campo'),
	(334, 'Cochrane', 52, 15, 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo'),
	(335, 'O\'Higgins', 52, 15, 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo'),
	(336, 'Tortel', 52, 15, 'Capitán Prat', 'Aysén del General Carlos Ibáñez del Campo'),
	(337, 'Natales', 53, 16, 'Última Esperanza', 'Magallanes y de la Antártica Chilena'),
	(338, 'Torres del Paine', 53, 16, 'Última Esperanza', 'Magallanes y de la Antártica Chilena'),
	(339, 'Laguna Blanca', 54, 16, 'Magallanes', 'Magallanes y de la Antártica Chilena'),
	(340, 'Punta Arenas', 54, 16, 'Magallanes', 'Magallanes y de la Antártica Chilena'),
	(341, 'Río Verde', 54, 16, 'Magallanes', 'Magallanes y de la Antártica Chilena'),
	(342, 'San Gregorio', 54, 16, 'Magallanes', 'Magallanes y de la Antártica Chilena'),
	(343, 'Porvenir', 55, 16, 'Tierra del Fuego', 'Magallanes y de la Antártica Chilena'),
	(344, 'Primavera', 55, 16, 'Tierra del Fuego', 'Magallanes y de la Antártica Chilena'),
	(345, 'Timaukel', 55, 16, 'Tierra del Fuego', 'Magallanes y de la Antártica Chilena'),
	(346, 'Cabo de Hornos', 56, 16, 'Antártica Chilena', 'Magallanes y de la Antártica Chilena'),
	(347, 'Antártica', 56, 16, 'Antártica Chilena', 'Magallanes y de la Antártica Chilena');
/*!40000 ALTER TABLE `comunas` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
